name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clear Cache
        run: rm -rf ~/.gradle/caches

      - name: Restore Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Ktlint
        run: ./gradlew lintKotlin

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Instrumentation Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: ./gradlew connectedDebugAndroidTest
